name: Setup Gradle environment
description: Common Gradle environment setup

runs:
  using: composite
  steps:
    - name: Setup JDK 8
      uses: actions/setup-java@v4.7.1
      with:
        distribution: zulu
        java-version: 8
        cache: gradle

    - name: Validate Gradle Wrapper
      uses: gradle/actions/wrapper-validation@v4.4.1

    - name: Init
      shell: bash
      run: |
        ./gradlew preparePatchingEnvironment
        ./pm.apply-patches
