name: Build

on:
  push:
    branches-ignore:
      - master
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codes
        uses: actions/checkout@v4.2.2

      - name: Setup environment
        uses: ./.github/actions/setup-gradle-env

      - name: Build
        uses: ./.github/actions/build
