# Copyright (c) 2020 anatawa12 and other contributors
# This file is part of fixRTM, released under GNU LGPL v3 with few exceptions
# See LICENSE at https://github.com/fixrtm/fixRTM for more details

name: No Add Import

on:
  push:

jobs:
  no-add-import:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Changelog check for CHANGELOG-SNAPSHOTS.md
        run: |
          if grep -R '+import ' src/main/rtm-patches src/main/ngtlib-patches ; then
            echo "::error::There are added imports"
            exit 1
          fi
