name: Release[Indev]
on:
  # TODO: Prevent dispatching in production release
  push:
    branches:
      - master

jobs:
  gen-version:
    name: Generate build serial
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.repository }}-gen-indev-build-serial
      cancel-in-progress: false
    outputs:
      version: ${{ steps.script.outputs.result }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Generate build serial
        id: script
        uses: actions/github-script@v7.0.1
        with:
          result-encoding: string
          script: |
            const script = require("./.github/workflows/script/gen-version.js");
            return await script({process, github, context, core});

  release:
    name: Release
    needs: gen-version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup environment
        uses: ./.github/actions/setup-gradle-env

      - name: Change mod version
        uses: ./.github/actions/patch-mod-version
        with:
          version: ${{ needs.gen-version.outputs.version }}

      - name: Build
        uses: ./.github/actions/build

      - name: Release
        uses: softprops/action-gh-release@v2.3.2
        with:
          name: "[Indev] ${{ needs.gen-version.outputs.version }}"
          tag_name: ${{ needs.gen-version.outputs.version }}
          prerelease: true
          generate_release_notes: true
          files: ./build/libs/*
          fail_on_unmatched_files: true
